# Generated by Django 5.2.3 on 2025-07-30 04:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_id', models.CharField(max_length=20, unique=True)),
                ('alias_name', models.CharField(max_length=255)),
                ('crime_type', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('last_known_location', models.CharField(default='Unknown', max_length=255)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='criminals/')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('image', models.ImageField(upload_to='missing_persons/')),
                ('missing_from', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missingperson.missingperson')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
