# Generated by Django 5.2.3 on 2025-08-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalrecord',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
